items:
  combat:
    bow:
      custom_model_data: 128
      price: 2
    arrow:
      custom_model_data: 128
      price: 2
    cooked_beef:
      custom_model_data: 128
      price: 1
    skeleton_killer:
      custom_model_data: 128
      price: 4
    stan_grenade:
      custom_model_data: 128
      price: 2
    werewolf_axe:
      custom_model_data: 128
      price: 4
    invisible_potion:
      custom_model_data: 128
      price: 4
    trident_of_rancor:
      custom_model_data: 128
      price: 3
  support:
    speed_potion:
      custom_model_data: 128
      price: 0
    heart_of_fortuneteller:
      custom_model_data: 128
      price: 4
    pray_of_knight:
      custom_model_data: 128
      price: 0
    providence_of_knight:
      custom_model_data: 128
      price: 2
    eye_of_mad:
      custom_model_data: 128
      price: 4
    sacred_cross:
      custom_model_data: 128
      price: 2
    eye_of_providence:
      custom_model_data: 128
      price: 2
    talisman:
      custom_model_data: 128
      price: 1
    ash_of_medium:
      custom_model_data: 128
      price: 4
  other:
    blunt:
      custom_model_data: 128
    bread:
      custom_model_data: 128
    telescope:
      custom_model_data: 128
numbers:
  skeleton_per_population: 10.0
  emerald_odds: 0.5
  time_day: 120
  time_night: 120
  time_first_day: 60
  max_player: 16
  jobs:
    3: "w=1"
    4: "w=1"
    5: "w=1"
    6: "w=1,m=1"
    7: "w=1,m=1"
    8: "w=2,m=1"
    9: "w=2,m=1"
    10: "w=2,m=1,v=1"
    11: "w=2,m=1,v=1"
    12: "w=3,m=1,v=1"
    13: "w=3,m=1,v=1"
    14: "w=3,m=1,v=1"
    15: "w=3,m=1,v=1,b=1,s=1"
    16: "w=3,m=1,v=1,b=1,s=1"
