name: NewJinroRPG
version: 1.3-SNAPSHOT
main: net.tagucha.jrpg.PluginMain
description: This game was created by WhiteTails, which is one of YouTuber groups, and this plugin was created by tagucha.
api-version: 1.18
author: tagucha
commands:
  jinro:
    usage: /jinro ???
    description: Let's play Jinro RPG.
permissions:
  jinro:
    description: To do everything of JinroRPG
    default: false
    children:
      command:
        description: To perform all the commands of JinroRPG
        default: false
        children:
          start:
            description: To start a game JinroRPG
            default: false
          spawn:
            description: To spawn shop keeper
            default: false
          sign:
            description: To get a sign item
            default: false
          give:
            description: To get items of the game
            default: false